project:
  type: book

book:
  title: "Cloud for Earth Science"
  author: "NASA Openscapes Community"
  date: "6/2/2021"
  chapters:
    - index.md
# part: Getting Started
    - docs/getting_started/earthdata_login.md
    - docs/getting_started/earthdata_login_test.md
    - docs/getting_started/authentication.md
    - docs/getting_started/netrc_file.md
    - docs/getting_started/inline_authentication.md
# part: Backgound
#   - cloud_optimized_data_formats.md
# part: NASA Cloud Data Discovery
#   - /discovery/discovery.md
    - docs/discovery/Navigate_CMR_STAC.ipynb  
    - docs/access/access.md
    - docs/references.md

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: report
  epub:
    cover-image: cover.png

